[tool.poetry]
name = "muskivml"
version = "0.1.0"
description = "Personalized playlist creator and recommender"
authors = ["Nasr Kasrin <n42r.me@gmail.com>"]
license = "GNU General Public License v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
spotipy = "^2.23.0"


[tool.poetry.group.dev.dependencies]
email-validator = "^2.1.0.post1"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
