version: 1
disable_existing_loggers: true
formatters:
  json:
    (): virtmulib.vml_logging.json_logger_fact
    format: '%(asctime)s - %(levelname)s - %(name)s - %(funcName)s:%(lineno)d - %(message)s'
  console:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  file:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(funcName)s:%(lineno)d - %(message)s'
handlers:
  console:
    level: DEBUG
    formatter: console
    class: logging.StreamHandler
    stream:  ext://sys.stdout
  file:
    level: DEBUG
    formatter: json
    class: logging.FileHandler
    filename: vml.log
  firebase:
    class: virtmulib.vml_logging.CloudLogHandler
    formatter: json
    level: DEBUG
loggers:
  '':
    handlers:
      - console
      - firebase
      - file
    level: DEBUG
    propagate: true
  # firebase:
  #   handlers:
  #   level: DEBUG
  #   propagate: true
  # file:
  #   handlers:
  #   level: DEBUG
  #   propagate: true